apiVersion: cronjob.tutorial.kubebuilder.io/v1
kind: CronJob
metadata:
  labels:
    app.kubernetes.io/name: cronjob
    app.kubernetes.io/instance: cronjob-second
    app.kubernetes.io/part-of: cronjob
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/created-by: cronjob
  name: cronjob-second
spec:
  schedule: "*/1 * * * *"
  startingDeadlineSeconds: 60
  concurrencyPolicy: Allow # explicitly specify, but Allow is also default.
  jobTemplate:
    spec:
      template:
        spec:
          containers:
          - name: second
            image: busybox
            args:
            - /bin/sh
            - -c
            - date; echo What hath dog wrought
          restartPolicy: OnFailure

